/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cap1.C
**     Project   : ProjectPulseCapture
**     Processor : MC9S12XS128MAL
**     Beantype  : Capture
**     Version   : Bean 02.201, Driver 01.17, CPU db: 3.00.003
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2009-12-6, 13:30
**     Abstract  :
**         This bean "Capture" simply implements the capture function
**         of timer. The counter counts the same way as in free run mode. On
**         the selected edge of the input signal (on the input pin), the current
**         content of the counter register is written into the capture
**         register and the OnCapture event is called.
**     Settings  :
**             Timer capture encapsulation : Capture
**
**         Timer
**             Timer                   : TIM_Counter
**             Counter shared          : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**           Maximal time for capture register
**             Xtal ticks              : 8388608
**             microseconds            : 524288
**             milliseconds            : 524
**             seconds                 : 1
**             seconds (real)          : 0.5242880
**             Hz                      : 2
**           One tick of timer is
**             microseconds            : 8
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Capture                : TC3       [86]
**              Counter                : TCNT      [68]
**              Mode                   : TIOS      [64]
**              Run                    : TSCR1     [70]
**              Prescaler              : TSCR2     [77]
**
**         Used input pin              : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       12            |  PT3_IOC3
**             ----------------------------------------------------
**
**         Port name                   : T
**         Bit number (in port)        : 3
**         Bit mask of the port        : 8
**
**         Signal edge/level           : both
**         Priority                    : 
**         Pull option                 : off
**
**     Contents  :
**         Reset           - byte Cap1_Reset(void);
**         GetCaptureValue - byte Cap1_GetCaptureValue(Cap1_TCapturedValue *Value);
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


/* MODULE Cap1. */

#include "Cap1.h"

#pragma DATA_SEG Cap1_DATA
#pragma CODE_SEG Cap1_CODE

volatile word Cap1_CntrState;          /* Content of counter */

/*
** ===================================================================
**     Method      :  Cap1_Reset (bean Capture)
**
**     Description :
**         This method resets the counter register (see implementation
**         note in <General Info>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte Cap1_Reset(word *Value)

**  This method is implemented as a macro. See Cap1.h file.  **
*/

/*
** ===================================================================
**     Method      :  Cap1_GetCaptureValue (bean Capture)
**
**     Description :
**         This method gets the last value captured by enabled timer.
**         Note: one tick of timer is
**               8 us in high speed mode
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the content of the
**                           capture register
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte Cap1_GetCaptureValue(Cap1_TCapturedValue *Value)

**  This method is implemented as a macro. See Cap1.h file.  **
*/

/*
** ===================================================================
**     Method      :  Cap1_Init (bean Capture)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Cap1_Init(void)
{
  Cap1_CntrState = 0;                  /* Initial state of variable */
  /* PTPSR: PTPS7=0,PTPS6=0,PTPS5=1,PTPS4=1,PTPS3=1,PTPS2=1,PTPS1=1,PTPS0=1 */
  setReg8(PTPSR, 63);                  /* Set prescaler register according to the selected high speed CPU mode */ 
  /* TCTL4: EDG3B=1,EDG3A=1 */
  setReg8Bits(TCTL4, 192);             /* Enable capture function */ 
}


/* END Cap1. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [04.12]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
