/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : EC161.H
**     Project   : ProjectPulseCapture
**     Processor : MC9S12XS128MAL
**     Beantype  : EventCntr16
**     Version   : Bean 02.132, Driver 01.15, CPU db: 3.00.003
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2009-12-6, 11:25
**     Abstract  :
**         This bean "EventCntr16" implements an 16-bit event counter.
**         It counts the external events (specified edges of the external
**         signal). It uses a hardware timer counter.
**         The counter width is extended or taperred to 16 bits.
**     Settings  :
**         Timer name                  : PACNT [16-bit]
**
**         Counting mode               : Simple counter
**
**         Used input pin              : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       18            |  PT7_IOC7_PWM7
**             ----------------------------------------------------
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**         Counter register            : PACNT     [98]
**         Mode register               : PACTL     [96]
**         Run register                : PACTL     [96]
**     Contents  :
**         Reset        - byte EC161_Reset(void);
**         GetNumEvents - byte EC161_GetNumEvents(word *Value);
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __EC161
#define __EC161

/* MODULE EC161. */

#include "Cpu.h"

#pragma CODE_SEG EC161_CODE
#pragma DATA_SEG EC161_DATA

byte EC161_Reset(void);
/*
** ===================================================================
**     Method      :  EC161_Reset (bean EventCntr16)
**
**     Description :
**         This method resets the external event counter (sets it to
**         zero).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
** ===================================================================
*/

byte EC161_GetNumEvents(word *Value);
/*
** ===================================================================
**     Method      :  EC161_GetNumEvents (bean EventCntr16)
**
**     Description :
**         This method returns the number of the external events.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the returned number of
**                           the external events
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_OVERFLOW - Timer overflow
** ===================================================================
*/

void EC161_Init(void);
/*
** ===================================================================
**     Method      :  EC161_Init (bean EventCntr16)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma CODE_SEG __NEAR_SEG NON_BANKED
__interrupt void EC161_Interrupt(void);
#pragma CODE_SEG EC161_CODE
/*
** ===================================================================
**     Method      :  EC161_Interrupt (bean EventCntr16)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma CODE_SEG DEFAULT

/* END EC161. */

#endif /* ifndef __EC161 */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [04.12]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
