/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.C
**     Project   : MotorDrive0
**     Processor : MC9S12XDT256BMPV
**     Beantype  : MC9S12XDT384_112
**     Version   : Bean 02.002, Driver 02.03, CPU db: 2.87.216
**     Datasheet : MC9S12XDP512RMV2 Rev. 2.18 May 2008
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2010-5-9, 1:48
**     Abstract  :
**         This bean "MC9S12XDT384_112" implements properties, methods,
**         and events of the CPU.
**     Settings  :
**
**     Contents  :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE Cpu. */

#include "PWM0.h"
#include "PWM1.h"
#include "PWM2.h"
#include "PWM3.h"
#include "PWM4.h"
#include "PWM5.h"
#include "AS1.h"
#include "FC1.h"
#include "Events.h"
#include "Cpu.h"

#define CGM_DELAY  5119UL

#pragma DATA_SEG DEFAULT
#pragma CODE_SEG DEFAULT


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR reegister */
#pragma CODE_SEG __NEAR_SEG NON_BANKED


/*
** ===================================================================
**     Method      :  Cpu_Cpu_Interrupt (bean MC9S12XDT384_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_Interrupt)
{
  asm(BGND);
}


#pragma CODE_SEG DEFAULT

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (bean MC9S12XDT384_112)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (bean MC9S12XDT384_112)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (bean MC9S12XDT384_112)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (bean MC9S12XDT384_112)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  PE_low_level_init (bean MC9S12XDT384_112)
**
**     Description :
**         Initializes beans and provides common register initialization. 
**         The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Int. priority initialization */
  /*                                        No. Address Pri XGATE Name          Description */
  setReg8(INT_CFADDR, 208);             
  setReg8(INT_CFDATA3, 4);             /*  0x6B  0xFFD6   4   no   ivVsci0       used by PE */ 
  /* Initialization of RAM Protection (MMC module) */
  /* RAMXGU: ??=1,XGU6=1,XGU5=1,XGU4=1,XGU3=1,XGU2=1,XGU1=1,XGU0=1 */
  setReg8(RAMXGU, 255);                 
  /* RAMSHL: ??=1,SHL6=1,SHL5=1,SHL4=1,SHL3=1,SHL2=1,SHL1=1,SHL0=1 */
  setReg8(RAMSHL, 255);                 
  /* RAMSHU: ??=1,SHU6=1,SHU5=1,SHU4=1,SHU3=1,SHU2=1,SHU1=1,SHU0=1 */
  setReg8(RAMSHU, 255);                 
  /* RAMWPC: RWPE=0,??=0,??=0,??=0,??=0,??=0,AVIE=0,AVIF=0 */
  setReg8(RAMWPC, 0);                   
  /* Common initialization of the CPU registers */
  /* PWME: PWME7=0,PWME6=0,PWME5=0,PWME4=0,PWME3=0,PWME2=0,PWME1=0,PWME0=0 */
  setReg8(PWME, 0);                     
  /* PWMCTL: CON45=0,CON23=0,CON01=0,PSWAI=0,PFRZ=0 */
  clrReg8Bits(PWMCTL, 124);             
  /* PWMCAE: CAE5=0,CAE4=0,CAE3=0,CAE2=0,CAE1=0,CAE0=0 */
  clrReg8Bits(PWMCAE, 63);              
  /* PWMPOL: PPOL5=1,PPOL4=1,PPOL3=1,PPOL2=1,PPOL1=1,PPOL0=1 */
  setReg8Bits(PWMPOL, 63);              
  /* PTP: PTP5=1,PTP4=1,PTP3=1,PTP2=1,PTP1=1,PTP0=1 */
  setReg8Bits(PTP, 63);                 
  /* DDRP: DDRP5=1,DDRP4=1,DDRP3=1,DDRP2=1,DDRP1=1,DDRP0=1 */
  setReg8Bits(DDRP, 63);                
  /* PTS: PTS1=1 */
  setReg8Bits(PTS, 2);                  
  /* DDRS: DDRS1=1,DDRS0=0 */
  clrSetReg8Bits(DDRS, 1, 2);           
  /* PITCFLMT: PITE=0 */
  clrReg8Bits(PITCFLMT, 128);           
  /* PITCE: PCE0=0 */
  clrReg8Bits(PITCE, 1);                
  /* PITINTE: PINTE0=0 */
  clrReg8Bits(PITINTE, 1);              
  /* PITMTLD0: PMTLD7=0,PMTLD6=0,PMTLD5=0,PMTLD4=0,PMTLD3=0,PMTLD2=0,PMTLD1=0,PMTLD0=0 */
  setReg8(PITMTLD0, 0);                 
  /* PITMUX: PMUX0=0 */
  clrReg8Bits(PITMUX, 1);               
  /* CRGINT: LOCKIE=0,SCMIE=0 */
  clrReg8Bits(CRGINT, 18);              
  /* VREGCTRL: LVIE=0 */
  clrReg8Bits(VREGCTRL, 2);             
  /* COPCTL: WCOP=0,RSBCK=0,WRTMASK=0,??=0,??=0,CR2=0,CR1=0,CR0=0 */
  setReg8(COPCTL, 0);                   
  /* RDRIV: RDPK=0,RDPE=0,RDPB=0,RDPA=0 */
  clrReg8Bits(RDRIV, 147);              
  /* RDR1AD1: RDR1AD115=0,RDR1AD114=0,RDR1AD113=0,RDR1AD112=0,RDR1AD111=0,RDR1AD110=0,RDR1AD19=0,RDR1AD18=0 */
  setReg8(RDR1AD1, 0);                  
  /* RDRH: RDRH7=0,RDRH6=0,RDRH5=0,RDRH4=0,RDRH3=0,RDRH2=0,RDRH1=0,RDRH0=0 */
  setReg8(RDRH, 0);                     
  /* RDRJ: RDRJ7=0,RDRJ6=0,RDRJ1=0,RDRJ0=0 */
  clrReg8Bits(RDRJ, 195);               
  /* RDRM: RDRM7=0,RDRM6=0,RDRM5=0,RDRM4=0,RDRM3=0,RDRM2=0,RDRM1=0,RDRM0=0 */
  setReg8(RDRM, 0);                     
  /* RDRP: RDRP7=0,RDRP6=0,RDRP5=0,RDRP4=0,RDRP3=0,RDRP2=0,RDRP1=0,RDRP0=0 */
  setReg8(RDRP, 0);                     
  /* RDRS: RDRS7=0,RDRS6=0,RDRS5=0,RDRS4=0,RDRS3=0,RDRS2=0,RDRS1=0,RDRS0=0 */
  setReg8(RDRS, 0);                     
  /* RDRT: RDRT7=0,RDRT6=0,RDRT5=0,RDRT4=0,RDRT3=0,RDRT2=0,RDRT1=0,RDRT0=0 */
  setReg8(RDRT, 0);                     
  /* RDR1AD0: RDR1AD07=0,RDR1AD06=0,RDR1AD05=0,RDR1AD04=0,RDR1AD03=0,RDR1AD02=0,RDR1AD01=0,RDR1AD00=0 */
  setReg8(RDR1AD0, 0);                  
  /* IRQCR: IRQEN=0 */
  clrReg8Bits(IRQCR, 64);               
  /* ### MC9S12XDT384_112 "Cpu" init code ... */
  /* ### Programable pulse generation "PWM0" init code ... */
  PWM0_Init();
  /* ### Programable pulse generation "PWM1" init code ... */
  PWM1_Init();
  /* ### Programable pulse generation "PWM2" init code ... */
  PWM2_Init();
  /* ### Programable pulse generation "PWM3" init code ... */
  PWM3_Init();
  /* ### Programable pulse generation "PWM4" init code ... */
  PWM4_Init();
  /* ### Programable pulse generation "PWM5" init code ... */
  PWM5_Init();
  /* ### Asynchro serial "AS1" init code ... */
  AS1_Init();
  /* ### Free running 16-bit counter "FC1" init code ... */
  /* PITLD0: PLD15=0,PLD14=1,PLD13=0,PLD12=1,PLD11=0,PLD10=0,PLD9=0,PLD8=0,PLD7=0,PLD6=0,PLD5=0,PLD4=0,PLD3=0,PLD2=0,PLD1=0,PLD0=0 */
  setReg16(PITLD0, 20480);             /* Store given value to the compare register */ 
  /* PITCE: PCE0=1 */
  setReg8Bits(PITCE, 1);               /* Enable Timer */ 
 /* Common peripheral initialization - ENABLE */
  /* PITCFLMT: PITE=1 */
  setReg8Bits(PITCFLMT, 128);           
  asm {
    PSHA
    LDAA #0
    TFR A,CCRH
    PULA
  }
  __EI();                              /* Enable interrupts */
}

#pragma CODE_SEG __NEAR_SEG NON_BANKED

/*
** ===================================================================
**     Method      :  _EntryPoint (bean MC9S12XDT384_112)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */
#pragma OPTION ADD "-Onf"              /* 'Create Sub-Functions with Common Code optimalization' must be disabled because stack is not yet initialized */

#pragma NO_FRAME
#pragma NO_EXIT
void _EntryPoint(void)
{
  /* ### MC9S12XDT384_112 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* MMCCTL1: ??=0,??=0,??=0,??=0,??=0,EROMON=0,ROMHM=0,ROMON=1 */
  setReg8(MMCCTL1, 1);                  
  /* DIRECT: DP15=0,DP14=0,DP13=0,DP12=0,DP11=0,DP10=0,DP9=0,DP8=0 */
  setReg8(DIRECT, 0);                   
  /* IVBR: IVB_ADDR=255 */
  setReg8(IVBR, 255);                   
  /* ECLKCTL: NECLK=0,NCLKX2=1,??=0,??=0,??=0,??=0,EDIV1=0,EDIV0=0 */
  setReg8(ECLKCTL, 64);                 
  /*  System clock initialization */
  /* CLKSEL: PLLSEL=0,PSTP=0,??=0,??=0,PLLWAI=0,??=0,RTIWAI=0,COPWAI=0 */
  setReg8(CLKSEL, 0);                  /* Select clock source from XTAL and set bits in CLKSEL reg. */ 
  /* PLLCTL: CME=1,PLLON=0,AUTO=1,ACQ=1,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 177);                /* Disable the PLL */ 
  /* SYNR: ??=0,??=0,SYN5=0,SYN4=0,SYN3=0,SYN2=1,SYN1=0,SYN0=0 */
  setReg8(SYNR, 4);                    /* Set the multiplier register */ 
  /* REFDV: ??=0,??=0,REFDV5=0,REFDV4=0,REFDV3=0,REFDV2=0,REFDV1=0,REFDV0=1 */
  setReg8(REFDV, 1);                   /* Set the divider register */ 
  /* PLLCTL: CME=1,PLLON=1,AUTO=1,ACQ=1,FSTWKP=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 241);                 
  while(!CRGFLG_LOCK) {                /* Wait until the PLL is within the desired tolerance of the target frequency */
  }
  /* CLKSEL: PLLSEL=1 */
  setReg8Bits(CLKSEL, 128);            /* Select clock source from PLL */ 
  /*** End of PE initialization code after reset ***/
  __asm("jmp _Startup");               /* Jump to C startup code */
}

#pragma CODE_SEG DEFAULT
/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [04.12]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
