/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TI2.C
**     Project   : PulseCapture
**     Processor : MC9S12XS128MAL
**     Beantype  : TimerInt
**     Version   : Bean 02.157, Driver 01.18, CPU db: 3.00.003
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2009-12-11, 20:46
**     Abstract  :
**         This bean "TimerInt" implements a periodic interrupt.
**         When the bean and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : PIT1 (16-bit)
**         Compare name                : PITload1
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 68966 Hz
**           Initial period/frequency
**             Xtal ticks              : 15204120
**             microseconds            : 950258
**             milliseconds            : 950
**             seconds                 : 1
**             seconds (real)          : 0.9502575
**             Hz                      : 1
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : PITCNT1   [846]
**              Mode                   : PITCFLMT  [832]
**              Run                    : PITCE     [834]
**
**         Compare registers
**              Compare                : PITLD1    [844]
**
**         Flip-flop registers
**     Contents  :
**         No public methods
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE TI2. */

#include "Events.h"
#include "TI2.h"

#pragma DATA_SEG TI2_DATA
#pragma CODE_SEG TI2_CODE
#pragma CONST_SEG DEFAULT


/* Internal method prototypes */


/* End of Internal methods declarations */

/*lint -save -e718 -e746 -e937 -e957 -e18 -e516 -e532 -e14 Disable MISRA rule (71,72,25) checking. */
/*
** ===================================================================
**     Method      :  TI2_Interrupt (bean TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the bean.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(TI2_Interrupt)
{
  PITTF = 2;                           /* Reset interrupt request flag */
  TI2_OnInterrupt();                   /* Invoke user event */
}

#pragma CODE_SEG TI2_CODE
/*lint -restore */

/* END TI2. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [04.12]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
