/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ATC1.H
**     Project   : SmartCar
**     Processor : MC9S12DG128BCPV
**     Beantype  : ADC
**     Version   : Bean 01.489, Driver 01.15, CPU db: 2.87.345
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2010-3-13, 16:29
**     Abstract  :
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**         This device is designed for fast A/D conversions.
**     Settings  :
**         AD control register         : ATD1CTL2    [290]
**         AD control register         : ATD1CTL3    [291]
**         AD control register         : ATD1CTL4    [292]
**         AD control register         : ATD1CTL5    [293]
**         AD control register         : ATD1STAT0   [294]
**         AD control register         : ATD1STAT1   [299]
**         AD control register         : ATD1CTL23   [290]
**         AD control register         : ATD1CTL45   [292]
**         AD control register         : ATD1TEST1   [297]
**         AD control register         : ATD1DIEN    [301]
**         Priority                    : 
**         User handling procedure     : not specified
**         Number of conversions       : 8
**         AD resolution               : 8-bit
**
**         Input pins
**
**              Port name              : AD1
**              Bit number (in port)   : 0
**              Bit mask of the port   : 1
**              Port data register     : PORTAD1     [303]
**
**         Initialization:
**              Conversion             : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-4
**     Contents  :
**         Measure    - byte ATC1_Measure(bool WaitForResult);
**         GetValue16 - byte ATC1_GetValue16(word *Values);
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __ATC1
#define __ATC1

/* MODULE ATC1. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"
#include "Cpu112.h"

#pragma DATA_SEG ATC1_DATA
#pragma CODE_SEG ATC1_CODE


#define ATC1_DisableTrigger ATC1_Stop

byte ATC1_Measure(bool WaitForResult);
/*
** ===================================================================
**     Method      :  ATC1_Measure (bean ADC)
**
**     Description :
**         This method performs one measurement on all channels that
**         are set in the bean inspector. (Note: If the <number of
**         conversions> is more than one the conversion of A/D
**         channels is performed specified number of times.)
**     Parameters  :
**         NAME            - DESCRIPTION
**         WaitForResult   - Wait for a result
**                           of a conversion. If the <interrupt
**                           service> is disabled and a <number of
**                           conversions> is greater than 1, the
**                           WaitForResult parameter is ignored and
**                           the method waits for each result every
**                           time.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already
**                           running
** ===================================================================
*/

byte ATC1_GetValue16(word *Values);
/*
** ===================================================================
**     Method      :  ATC1_GetValue16 (bean ADC)
**
**     Description :
**         This method returns the last measured values of all
**         channels justified to the left. Compared with <GetValue>
**         method this method returns more accurate result if the
**         <number of conversions> is greater than 1 and <AD
**         resolution> is less than 16 bits. In addition, the user
**         code dependency on <AD resolution> is eliminated.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Values          - Pointer to the array that
**                           contains the measured data.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun
**                           flag was detected after last value(s)
**                           was obtained (for example by GetValue).
**                           This error may not be supported on some
**                           CPUs (see generated code).
** ===================================================================
*/

void ATC1_Init(void);
/*
** ===================================================================
**     Method      :  ATC1_Init (bean ADC)
**
**     Description :
**         Initializes the associated peripheral(s) and the bean's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma CODE_SEG DEFAULT

/* END ATC1. */

#endif /* ifndef __ATC1 */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [04.12]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
