/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cap2.H
**     Project   : SmartCar
**     Processor : MC9S12DG128BCPV
**     Beantype  : Capture
**     Version   : Bean 02.201, Driver 01.17, CPU db: 2.87.345
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2010-3-9, 16:49
**     Abstract  :
**         This bean "Capture" simply implements the capture function
**         of timer. The counter counts the same way as in free run mode. On
**         the selected edge of the input signal (on the input pin), the current
**         content of the counter register is written into the capture
**         register and the OnCapture event is called.
**     Settings  :
**             Timer capture encapsulation : Capture
**
**         Timer
**             Timer                   : ECT_Counter
**             Counter shared          : Yes
**
**         High speed mode
**             Prescaler               : divide-by-2
**           Maximal time for capture register
**             Xtal ticks              : 262144
**             microseconds            : 16384
**             milliseconds            : 16
**             seconds (real)          : 0.0163840
**             Hz                      : 61
**           One tick of timer is
**             nanoseconds             : 250
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Capture                : TC7       [94]
**              Counter                : TCNT      [68]
**              Mode                   : TIOS      [64]
**              Run                    : TSCR1     [70]
**              Prescaler              : TSCR2     [77]
**
**         Used input pin              : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       18            |  PT7_IOC7
**             ----------------------------------------------------
**
**         Port name                   : T
**         Bit number (in port)        : 7
**         Bit mask of the port        : 128
**
**         Signal edge/level           : rising
**         Priority                    : 
**         Pull option                 : off
**
**     Contents  :
**         Reset           - byte Cap2_Reset(void);
**         GetCaptureValue - byte Cap2_GetCaptureValue(Cap2_TCapturedValue *Value);
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __Cap2
#define __Cap2

/* MODULE Cap2. */

#include "Cpu112.h"

#pragma DATA_SEG Cap2_DATA
#pragma CODE_SEG Cap2_CODE

#define Cap2_TCapturedValue word /* Type of the captured value */
#define Cap2_PRESCALER_VALUE 2U        /* Initial prescaler value of the timer */
#define Cap2_TIMER_INPUT_CLOCK 8000000UL /* DEPRECATED. Initial timer input clock frequency [Hz] */
#define Cap2_COUNTER_INPUT_CLOCK_HZ 4000000UL /* Initial counter input clock frequency [Hz] */
/* High speed mode constants */
#define Cap2_PRESCALER_VALUE_HIGH 2U   /* Initial prescaler value of the timer in high speed mode */
#define Cap2_TIMER_INPUT_CLOCK_HIGH 8000000UL /* DEPRECATED. Timer input clock frequency [Hz] in high speed mode */
#define Cap2_COUNTER_INPUT_CLOCK_HZ_HIGH 4000000UL /* Initial counter input clock frequency [Hz] in high speed mode */

extern volatile word Cap2_CntrState;   /* Content of counter */

#define Cap2_Reset() (Cap2_CntrState = TCNT , ERR_OK)
/*
** ===================================================================
**     Method      :  Cap2_Reset (bean Capture)
**
**     Description :
**         This method resets the counter register (see implementation
**         note in <General Info>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define Cap2_GetCaptureValue(Value) \
 (*(Cap2_TCapturedValue*)(Value) = (TC7 - Cap2_CntrState), ERR_OK)
/*
** ===================================================================
**     Method      :  Cap2_GetCaptureValue (bean Capture)
**
**     Description :
**         This method gets the last value captured by enabled timer.
**         Note: one tick of timer is
**               250 ns in high speed mode
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the content of the
**                           capture register
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

void Cap2_Init(void);
/*
** ===================================================================
**     Method      :  Cap2_Init (bean Capture)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma CODE_SEG DEFAULT

/* END Cap2. */

#endif /* ifndef __Cap2 */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [04.12]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
