/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu112.H
**     Project   : SmartCar
**     Processor : MC9S12DG128BCPV
**     Beantype  : MC9S12DG128_112
**     Version   : Bean 02.001, Driver 02.03, CPU db: 2.87.345
**     Datasheet : 9S12DT128BDGV1/D V01.05
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2010-3-8, 15:12
**     Abstract  :
**         This bean "MC9S12DG128_112" implements properties, methods,
**         and events of the CPU.
**     Settings  :
**
**     Contents  :
**         EnableInt   - void Cpu112_EnableInt(void);
**         DisableInt  - void Cpu112_DisableInt(void);
**         SetWaitMode - void Cpu112_SetWaitMode(void);
**         SetStopMode - void Cpu112_SetStopMode(void);
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __Cpu112
#define __Cpu112

/* Active configuration define symbol */
#define PEcfg_XS256VAL 1

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"

/* MODULE Cpu112. */


#pragma DATA_SEG DEFAULT

#define CPU_BUS_CLK_HZ              8000000UL /* Initial value of the bus clock frequency in Hz */

#define CPU_INSTR_CLK_HZ            8000000UL /* Initial value of the instruction clock frequency in Hz */

#define CPU_EXT_CLK_HZ              16000000UL /* Value of the main clock frequency (crystal or external clock) in Hz */

#define CPU_CORE_HCS12                 /* Specification of the core type of the selected cpu */
#define CPU_DERIVATIVE_MC9S12DG128B    /* Name of the selected cpu derivative */
#define CPU_PARTNUM_MC9S12DG128BCPV    /* Part number of the selected cpu */

/* Global variables */

extern volatile byte CCR_reg;          /* Current CCR reegister */
/*Shadow variables*/

extern byte Shadow_M;                  /* Shadow variable for I/O beans */
extern byte Shadow_K;                  /* Shadow variable for I/O beans */

/* Entry point routine(s) prototypes */

#pragma CODE_SEG __NEAR_SEG NON_BANKED
void _EntryPoint(void);
/*
** ===================================================================
**     Method      :  _EntryPoint (bean MC9S12DG128_112)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* Interrupt routine(s) prototypes */

/* Forward declaration of the default interrupt routine(s) */
__interrupt void Cpu112_Interrupt(void);

#pragma CODE_SEG DEFAULT

#define Cpu112_SetStopMode()  {__asm("ANDCC #0x7F"); __asm("STOP"); }
/*
** ===================================================================
**     Method      :  Cpu112_SetStopMode (bean MC9S12DG128_112)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Cpu112_SetWaitMode()  __asm("WAI")
/*
** ===================================================================
**     Method      :  Cpu112_SetWaitMode (bean MC9S12DG128_112)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define   Cpu112_DisableInt()  __DI()  /* Disable interrupts */
/*
** ===================================================================
**     Method      :  Cpu112_DisableInt (bean MC9S12DG128_112)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define   Cpu112_EnableInt()  __EI()   /* Enable interrupts */
/*
** ===================================================================
**     Method      :  Cpu112_EnableInt (bean MC9S12DG128_112)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void PE_low_level_init(void);
/*
** ===================================================================
**     Method      :  PE_low_level_init (bean MC9S12DG128_112)
**
**     Description :
**         Initializes beans and provides common register initialization. 
**         The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* END Cpu112. */

#endif /* ifndef __Cpu112 */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [04.12]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
