/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : K0.H
**     Project   : SmartCar
**     Processor : MC9S12DG128BCPV
**     Beantype  : BitIO
**     Version   : Bean 02.072, Driver 03.11, CPU db: 2.87.345
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2010-3-8, 14:06
**     Abstract  :
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this bean are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       8             |  PK0_XADDR14
**             ----------------------------------------------------
**
**         Port name                   : K
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : 1
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PORTK     [50]
**         Port control register       : DDRK      [51]
**
**         Optimization for            : speed
**     Contents  :
**         SetDir - void K0_SetDir(bool Dir);
**         GetVal - bool K0_GetVal(void);
**         PutVal - void K0_PutVal(bool Val);
**         ClrVal - void K0_ClrVal(void);
**         SetVal - void K0_SetVal(void);
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef K0_H_
#define K0_H_

/* MODULE K0. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu112.h"

#pragma CODE_SEG K0_CODE
/*
** ===================================================================
**     Method      :  K0_GetVal (bean BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define K0_GetVal() ( \
    (bool)((getReg8(PORTK) & 1))       /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  K0_PutVal (bean BitIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void K0_PutVal(bool Val);

/*
** ===================================================================
**     Method      :  K0_ClrVal (bean BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**           a) direction = Input  : sets the output value to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define K0_ClrVal() ( \
    (void)clrReg8Bits(PORTK, 1)        /* BIT0=0 */, \
    Shadow_K &= (byte)~1               /* Set appropriate bit in shadow variable */ \
  )

/*
** ===================================================================
**     Method      :  K0_SetVal (bean BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**           a) direction = Input  : sets the output value to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define K0_SetVal() ( \
    (void)setReg8Bits(PORTK, 1)        /* BIT0=1 */, \
    Shadow_K |= (byte)1                /* Set appropriate bit in shadow variable */ \
  )

/*
** ===================================================================
**     Method      :  K0_SetDir (bean BitIO)
**
**     Description :
**         This method sets direction of the bean.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void K0_SetDir(bool Dir);

#pragma CODE_SEG DEFAULT

/* END K0. */
#endif /* #ifndef __K0_H_ */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [04.12]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
