/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : M4.H
**     Project   : SmartCar
**     Processor : MC9S12DG128BCPV
**     Beantype  : BitIO
**     Version   : Bean 02.072, Driver 03.11, CPU db: 2.87.345
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2010-3-8, 14:01
**     Abstract  :
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Methods of this bean are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       101           |  PM4_RxCAN0_RxCAN4_MOSI0
**             ----------------------------------------------------
**
**         Port name                   : M
**
**         Bit number (in port)        : 4
**         Bit mask of the port        : 16
**
**         Initial direction           : Output (direction can be changed)
**         Safe mode                   : yes
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PTM       [592]
**         Port control register       : DDRM      [594]
**
**         Optimization for            : speed
**     Contents  :
**         SetDir - void M4_SetDir(bool Dir);
**         GetVal - bool M4_GetVal(void);
**         PutVal - void M4_PutVal(bool Val);
**         ClrVal - void M4_ClrVal(void);
**         SetVal - void M4_SetVal(void);
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef M4_H_
#define M4_H_

/* MODULE M4. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu112.h"

#pragma CODE_SEG M4_CODE
/*
** ===================================================================
**     Method      :  M4_GetVal (bean BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define M4_GetVal() ( \
    (bool)((getReg8(PTM) & 16))        /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  M4_PutVal (bean BitIO)
**
**     Description :
**         This method writes the new output value.
**           a) direction = Input  : sets the new output value;
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes the value to the
**                                   appropriate pin
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void M4_PutVal(bool Val);

/*
** ===================================================================
**     Method      :  M4_ClrVal (bean BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**           a) direction = Input  : sets the output value to "0";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "0" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define M4_ClrVal() ( \
    (void)clrReg8Bits(PTM, 16)         /* PTM4=0 */, \
    Shadow_M &= (byte)~16              /* Set appropriate bit in shadow variable */ \
  )

/*
** ===================================================================
**     Method      :  M4_SetVal (bean BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**           a) direction = Input  : sets the output value to "1";
**                                   this operation will be shown on
**                                   output after the direction has
**                                   been switched to output
**                                   (SetDir(TRUE);)
**           b) direction = Output : directly writes "1" to the
**                                   appropriate pin
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define M4_SetVal() ( \
    (void)setReg8Bits(PTM, 16)         /* PTM4=1 */, \
    Shadow_M |= (byte)16               /* Set appropriate bit in shadow variable */ \
  )

/*
** ===================================================================
**     Method      :  M4_SetDir (bean BitIO)
**
**     Description :
**         This method sets direction of the bean.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void M4_SetDir(bool Dir);

#pragma CODE_SEG DEFAULT

/* END M4. */
#endif /* #ifndef __M4_H_ */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [04.12]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
